#!/bin/bash

# Clean and build targets
cd ..
make clean
make

for (( i = 0; i < 5; i++ )); do
    echo "=============================\n\n" >> valer_30m.txt
    ./genetic ./instances/br17.atsp 1800 >> valer_30m.txt &
    ./genetic ./instances/ft70.atsp 1800 >> valer_30m.txt &
    ./genetic ./instances/ftv33.atsp 1800 >> valer_30m.txt &
    ./genetic ./instances/ftv44.atsp 1800 >> valer_30m.txt &
    ./genetic ./instances/ftv55.atsp 1800 >> valer_30m.txt &
    ./genetic ./instances/ftv170.atsp 1800 >> valer_30m.txt &
    ./genetic ./instances/kro124p.atsp 1800 >> valer_30m.txt &
    ./genetic ./instances/rbg323.atsp 1800 >> valer_30m.txt &
    ./genetic ./instances/rbg358.atsp 1800 >> valer_30m.txt &
    ./genetic ./instances/rbg403.atsp 1800 >> valer_30m.txt &

    sleep 1860
done
